version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db
    environment:
      - DB_HOSTNAME=db
      - DB_DATABASE=adam_rms
      - DB_USERNAME=adam_rms
      - DB_PASSWORD=secret
      - DB_PORT=3306
      - DEV_MODE=true
      - CONFIG_ROOTURL=http://localhost:8080
      - CONFIG_AUTH_JWTKey=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      - CONFIG_EMAILS_ENABLED=Disabled
  db:
    image: mariadb:10.11
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=adam_rms
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=adam_rms
      - MYSQL_PASSWORD=secret
  mail:
    image: axllent/mailpit:v1.20
    profiles:
      - notifications
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8083:8025

volumes:
  db_data: null
